---
title: "lme_result_exp1"
author: "Jose Ossandon"
date: "14 December 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Result LM and ANOVA E299


```{r getting_data, results='hide', message=FALSE, warning=FALSE, echo=FALSE}

path       = "/Users/jossando/trabajo/E299"
setwd(path)

source("05_Code/02_Analysis/rcode/utilities/openGraphSaveGraph.R", chdir=T) # utilities by Kruschke from http://doingbayesiandataanalysis.blogspot.de/
#source("05_Code/02_Analysis/rcode/utilities/HDIofMCMC.R", chdir=T)
source("05_Code/02_Analysis/rcode/utilities/DBDA2E-utilities.R", chdir=T)
require(ggplot2)
require(plyr)
require(yarrr)
library(extrafont)
require(plotrix)
require(gridExtra)
require(lme4)
require(nlme)
require(MuMIn)

perf          = FALSE
logn          = FALSE                            # log-normal data model
avgs          = FALSE
factorial     = TRUE
exp = 1
if(exp==1){
  rem_subjects = c(3,9,13)
  pathfig = "LH2cross"}
if(exp==2){
  rem_subjects = c()
  pathfig  = c("LH2crossExp2","LH2crossAnti")
}
model         = "cond" # cond
thistask = 1
source("05_Code/02_Analysis/rcode/utilities/get_exp2_data.R")

datFrameOK$RespMF    = as.factor(datFrameOK$RespM) 
datFrameOK$HandCF    = as.factor(datFrameOK$HandC) 
datFrameOK$LegCF     = as.factor(datFrameOK$LegC) 
datFrameOK$trialintF     = as.factor(datFrameOK$trial_int) 
datFrameOK$taskF     = as.factor(datFrameOK$task) 
datFrameOK$subjIndxF = as.factor(datFrameOK$subjIndx)

contrasts(datFrameOK$RespMF) <- contr.sum(2)
contrasts(datFrameOK$HandCF) <- contr.sum(2)
contrasts(datFrameOK$LegCF) <- contr.sum(2)
#if(exp==2){
#contrasts(datFrameOK$taskF) <- contr.sum(2)
#}
contrasts(datFrameOK$trialintF) <- contr.sum(2)
contrasts(datFrameOK$subjIndxF) <- contr.sum(length(levels(datFrameOK$subjIndxF)))
datFrameOK$trial_RTms = datFrameOK$trial_RT*1000 
```
Subjects' averages analysis
```{r lmerresutls, echo=T}


datFrameAvg = ddply(datFrameOK,.(subjIndxF,LegCF,HandCF,RespMF,trialintF),summarize,trial_RTms=mean(trial_RTms))

#mixmodel1 = lmer(trial_RTms ~ LegCF*HandCF*RespMF*trialintF + (1|subjIndxF), data=datFrameAvg, REML=F)
#summary(mixmodel1)
#anova(mixmodel1)
# datFrameAvg = ddply(datFrameOK,.(subjIndxF,LegCF,cSxBF,cLxLF,trialintF),summarize,trial_RTms=mean(trial_RTms))
# mixmodel1 = lmer(trial_RTms ~ LegCF*cSxBF*cLxLF*trialintF + (1|subjIndxF), data=datFrameAvg, REML=F)
# summary(mixmodel1)
# anova(mixmodel1)
```
this are equivalent
```{r lmeaovresults, echo=T}
#mixmodel1 = lme(trial_RTms ~ LegCF*HandCF*RespMF*trialintF , random= ~1|subjIndxF, data=datFrameAvg)
#summary(mixmodel1)
#anova(mixmodel1)
anovamodel1 = aov(trial_RTms ~ RespMF*LegCF*HandCF*trialintF + Error(subjIndxF/(RespMF*LegCF*HandCF*trialintF)) , data=datFrameAvg)
summary(anovamodel1)
bf = anovaBF(trial_RTms ~ LegCF*HandCF*RespMF*trialintF + subjIndxF ,data=datFrameAvg, whichRandom="subjIndxF", whichModels="top", iterations=500000 )
bfInteraction = lmBF(trial_RTms ~ LegCF*HandCF*RespMF*trialintF + subjIndxF ,data=datFrameAvg, whichRandom="subjIndxF")
```
adding the factor response mode (external or anatomical) does not explain more
```{r respm, echo=T}
datFrameAvg = ddply(datFrameOK,.(subjIndxF,LegCF,HandCF,cLxLF,RespMF),summarize,trial_RTms=mean(trial_RTms))

#anovamodel1 = aov(trial_RTms ~ LegCF*HandCF*cLxLF + Error(subjIndxF) , data=datFrameAvg)
#summary(anovamodel1)
#anovamodel2 = aov(trial_RTms ~ LegCF*HandCF*RespMF + Error(subjIndxF) , data=datFrameAvg)
#summary(anovamodel2)


#noRespM = lmer(trial_RTms ~ LegCF*HandCF*cLxLF + (1|subjIndxF), data=datFrameAvg,REML=F)
#summary(noRespM)
wRespM = lmer(trial_RTms ~ LegCF*HandCF*RespMF + (1|subjIndxF), data=datFrameAvg,REML=F)
summary(wRespM)
anova(noRespM,wRespM)

```

adding the factor task (normal or external) explains a bit more
```{r respm, echo=T}
datFrameAvg = ddply(datFrameOK,.(subjIndxF,LegCF,HandCF,cLxLF,taskF),summarize,trial_RTms=mean(trial_RTms))

anovamodel1 = aov(trial_RTms ~ LegCF*HandCF*cLxLF + Error(subjIndxF) , data=datFrameAvg)
summary(anovamodel1)
anovamodel2 = aov(trial_RTms ~ LegCF*HandCF*cLxLF*taskF + Error(subjIndxF) , data=datFrameAvg)
summary(anovamodel2)


noTask = lmer(trial_RTms ~ LegCF*HandCF*cLxLF + (1|subjIndxF), data=datFrameAvg,REML=F)
summary(noTask)
wTask = lmer(trial_RTms ~ LegCF*HandCF*cLxLF*taskF + (1|subjIndxF), data=datFrameAvg,REML=F)
summary(wTask)
anova(noTask,wTask)

```